apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: devnotex
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30080
  type: NodePort


# kubectl apply -f K8S/backend/service.yaml