apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: devnotex
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: suryasuraj/devnotex-frontend
          imagePullPolicy: Always
          ports:
            - containerPort: 3000  
