apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: devnotex
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000  
      nodePort: 30081  
  type: NodePort
